### ISSUE TITLE
Can't build in iOS

### ISSUE THREAD

**Issue by kfukazawa-cq** [xmartlabs/react-native-line#10]
## Versions
- RN `0.51.0`

## Phenomenon
When I tried to build after done setting up, I got errors like bellow capture.

`LineLoginManager.xcodeprj/LineLoginManager.h`
![2018-01-26 20 12 08](https://user-images.githubusercontent.com/13075221/35437612-8cee61ce-02d6-11e8-9102-7916cad0df7a.png)

How can I fix this?

**Comment by mcousillas6** [comment]
Hey there, 
Can you show me the build log to see the errors?

**Comment by kfukazawa-cq** [comment]
Thank you.

logs are here.

 ```
In file included from /MyReactNativeApp/node_modules/react-native-line-sdk/ios/LineLoginManager.m:1:
/MyReactNativeApp/node_modules/react-native-line-sdk/ios/LineLoginManager.h:3:9: fatal error: 'LineSDK/LineSDK.h' file not found
#import <LineSDK/LineSDK.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.

```

I tried to clone your example project and buit it. then I got same errors.

**Comment by kfukazawa-cq** [comment]
@mcousillas6 

Android is working fine.
It would be great if this problem is fixed.

**Comment by mcousillas6** [comment]
just in case, did you run `pod install` on the iOS project before compiling?

**Comment by hatyaiapp** [comment]
@mcousillas6 I have same problem and I already run pod install first but its doesn't work

**Comment by oxygenyoyo2** [comment]
any update? I got this error as well, so I tried `pod install` not working.

**Comment by oxygenyoyo2** [comment]
I got the answer this one

[https://github.com/xmartlabs/react-native-line/issues/17#issuecomment-437581842](https://github.com/xmartlabs/react-native-line/issues/17#issuecomment-437581842)
