### ISSUE TITLE
'RNLine-Swift.h' file not found

### ISSUE THREAD

**Issue by purrsong-chong** [xmartlabs/react-native-line#107]
## Your environment
 
You can run (`react-native -v`) to obtain info and paste it below:

- React: 18.2.0
- React Native: 0.71.8
- React Native Line: ^2.2.0

## Description

In AppDelegate.mm, I can't import "RNLine-Swift.h"
I moved to top, and the problem is not solved

### Screenshots
![image](https://github.com/xmartlabs/react-native-line/assets/59009198/d902b5c9-a079-4841-a07c-2f46ae38f16e)

**Comment by emibotti** [comment]
Hey @purrsong-chong, how are you? 

It's possible that the issue could be related to the installation of pods and the generation of the bridging file for Objective-C and Swift. I recommend trying the following steps:

1. Open a terminal and navigate to your project's root directory.
2. Run the command `yarn` to ensure that all dependencies are up to date.
3. Change directory to the iOS folder using the command `cd ios`.
4. Run `pod install` to install the necessary pods for your project.
5. After the installation completes, try rebuilding your project.

If the problem persists, you can also try cleaning and rebuilding your project within Xcode:

1. Open Xcode and go to the "Product" menu.
2. Select "Clean" to clean your project.
3. Once the cleaning process finishes, select "Build" to rebuild your project.

Sometimes, Xcode may not recognize changes immediately, so cleaning and rebuilding the project can help in such cases.

I hope these suggestions help you resolve the issue. If you have any further questions or encounter any additional problems, please let me know!

**Comment by emibotti** [comment]
Hey @najil-12 ! Sure, this is the file:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'RNLineExample' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RNLineExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

It should be almost the same as the one created when starting a new project with `npx react-native ...`.

I see that you're encountering the same issue as posted in #108. Can you provide your pod installation result?

**Comment by najil-12** [comment]
> Hey @najil-12 ! Sure, this is the file:
> 
> ```
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> platform :ios, '12.4'
> install! 'cocoapods', :deterministic_uuids => false
> 
> target 'RNLineExample' do
>   config = use_native_modules!
>   use_frameworks! :linkage => :static
> 
>   # Flags change depending on the env values.
>   flags = get_default_flags()
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     # Hermes is now enabled by default. Disable by setting this flag to false.
>     # Upcoming versions of React Native may rely on get_default_flags(), but
>     # we make it explicit here to aid in the React Native upgrade process.
>     :hermes_enabled => true,
>     :fabric_enabled => flags[:fabric_enabled],
>     # Enables Flipper.
>     #
>     # Note that if you have use_frameworks! enabled, Flipper will not work and
>     # you should disable the next line.
>     # :flipper_configuration => FlipperConfiguration.enabled,
>     # An absolute path to your application root.
>     :app_path => "#{Pod::Config.instance.installation_root}/.."
>   )
> 
>   target 'RNLineExampleTests' do
>     inherit! :complete
>     # Pods for testing
>   end
> 
>   post_install do |installer|
>     react_native_post_install(
>       installer,
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
>     # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
>       end
>     end
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> end
> ```
> 
> It should be almost the same as the one created when starting a new project with `npx react-native ...`.
> 
> I see that you're encountering the same issue as posted in #108. Can you provide your pod installation result?

is there any need to change the deployment target to 11.0 as the documentation

**Comment by emibotti** [comment]
Great, thanks! Seems that the pods were installed all right. The deployment target set to 11.0 is the minimum. Probably you would want to set it to `12.4` as I did.

**Comment by purrsong-chong** [comment]
> Hey @purrsong-chong, how are you?
> 
> It's possible that the issue could be related to the installation of pods and the generation of the bridging file for Objective-C and Swift. I recommend trying the following steps:
> 
> 1. Open a terminal and navigate to your project's root directory.
> 2. Run the command `yarn` to ensure that all dependencies are up to date.
> 3. Change directory to the iOS folder using the command `cd ios`.
> 4. Run `pod install` to install the necessary pods for your project.
> 5. After the installation completes, try rebuilding your project.
> 
> If the problem persists, you can also try cleaning and rebuilding your project within Xcode:
> 
> 1. Open Xcode and go to the "Product" menu.
> 2. Select "Clean" to clean your project.
> 3. Once the cleaning process finishes, select "Build" to rebuild your project.
> 
> Sometimes, Xcode may not recognize changes immediately, so cleaning and rebuilding the project can help in such cases.
> 
> I hope these suggestions help you resolve the issue. If you have any further questions or encounter any additional problems, please let me know!

Thank you for your helps but problem is not solved :(

### Podfile
`
platform :ios, "13.0"
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

$FirebaseSDKVersion = '10.7.0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
end

target 'oauthTest' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true 

  target 'oauthTestTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
            if config.build_settings['DEVELOPMENT_TEAM'].nil?
              config.build_settings['DEVELOPMENT_TEAM'] = 'W5K79DJY7U'
            end
           end
      end
    end
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
`

### Result
`Installing AppAuth (1.6.2)
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBAEMKit (15.0.0)
Installing FBLazyVector (0.71.8)
Installing FBReactNativeSpec (0.71.8)
Installing FBSDKCoreKit (15.0.0)
Installing FBSDKCoreKit_Basics (15.0.0)
Installing FBSDKGamingServicesKit (15.0.0)
Installing FBSDKLoginKit (15.0.0)
Installing FBSDKShareKit (15.0.0)
Installing Firebase (10.7.0)
Installing FirebaseCore (10.7.0)
Installing FirebaseCoreInternal (10.8.0)
Installing Flipper (0.125.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.2.0.1)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)
Installing Flipper-Glog (0.5.0.5)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.4.3)
Installing FlipperKit (0.125.0)
Installing GTMAppAuth (2.0.0)
Installing GTMSessionFetcher (3.1.1)
Installing GoogleSignIn (7.0.0)
Installing GoogleUtilities (7.11.1)
Installing LineSDKSwift (5.8.2)
Installing OpenSSL-Universal (1.1.1100)
Installing PromisesObjC (2.2.0)
Installing RCT-Folly (2021.07.22.00)
Installing RCTRequired (0.71.8)
Installing RCTTypeSafety (0.71.8)
Installing RNAppleAuthentication (2.2.2)
Installing RNFBApp (17.5.0)
Installing RNGoogleSignin (10.0.1)
Installing RNLine (2.2.0)
Installing React (0.71.8)
Installing React-Codegen (0.71.8)
Installing React-Core (0.71.8)
Installing React-CoreModules (0.71.8)
Installing React-RCTActionSheet (0.71.8)
Installing React-RCTAnimation (0.71.8)
Installing React-RCTAppDelegate (0.71.8)
Installing React-RCTBlob (0.71.8)
Installing React-RCTImage (0.71.8)
Installing React-RCTLinking (0.71.8)
Installing React-RCTNetwork (0.71.8)
Installing React-RCTSettings (0.71.8)
Installing React-RCTText (0.71.8)
Installing React-RCTVibration (0.71.8)
Installing React-callinvoker (0.71.8)
Installing React-cxxreact (0.71.8)
Installing React-hermes (0.71.8)
Installing React-jsi (0.71.8)
Installing React-jsiexecutor (0.71.8)
Installing React-jsinspector (0.71.8)
Installing React-logger (0.71.8)
Installing React-perflogger (0.71.8)
Installing React-runtimeexecutor (0.71.8)
Installing ReactCommon (0.71.8)
Installing SocketRocket (0.6.0)
Installing Yoga (1.14.0)
Installing YogaKit (1.18.1)
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.71.8)
Installing libevent (2.1.12)
Installing react-native-fbsdk-next (11.2.1)
`

**Comment by najil-12** [comment]
> Great, thanks! Seems that the pods were installed all right. The deployment target set to 11.0 is the minimum. Probably you would want to set it to `12.4` as I did.

Yes i want 12.4 because if i change it to 11.0 then it is throwing another error

**Comment by najil-12** [comment]
> Hey @purrsong-chong, how are you?
> 
> It's possible that the issue could be related to the installation of pods and the generation of the bridging file for Objective-C and Swift. I recommend trying the following steps:
> 
> 1. Open a terminal and navigate to your project's root directory.
> 2. Run the command `yarn` to ensure that all dependencies are up to date.
> 3. Change directory to the iOS folder using the command `cd ios`.
> 4. Run `pod install` to install the necessary pods for your project.
> 5. After the installation completes, try rebuilding your project.
> 
> If the problem persists, you can also try cleaning and rebuilding your project within Xcode:
> 
> 1. Open Xcode and go to the "Product" menu.
> 2. Select "Clean" to clean your project.
> 3. Once the cleaning process finishes, select "Build" to rebuild your project.
> 
> Sometimes, Xcode may not recognize changes immediately, so cleaning and rebuilding the project can help in such cases.
> 
> I hope these suggestions help you resolve the issue. If you have any further questions or encounter any additional problems, please let me know!

please help this issue is still unresolved

**Comment by radenferyndra** [comment]
create an Expo exhibit configuration file named "app.config.js" in your project directory.
and add the following code: 

import 'dotenv/config';

export default {
  expo: {
    name: 'React Native Line',
    slug: 'react-native-line',
    version: '1.0.0',
    orientation: 'portrait',
    icon: './path/to/app-icon.png',
    splash: {
      image: './path/to/splash-image.png',
      resizeMode: 'contain',
      backgroundColor: '#ffffff',
    },
    platforms: ['ios', 'android'],
    sdkVersion: '42.0.0',
    description: 'A React Native Line Plugin',
    hooks: {
      postPublish: [
        {
          file: 'sentry-expo/upload-sourcemaps',
          config: {
            organization: 'your-organization',
            project: 'your-project',
            authToken: 'your-auth-token',
          },
        },
      ],
    },
    ios: {
      bundleIdentifier: 'com.yourcompany.reactnativeline',
      supportsTablet: true,
      config: {
        usesNonExemptEncryption: false,
        entitlements: {
          'com.apple.developer.applesignin': ['Default'],
        },
      },
      googleServicesFile: './path/to/google-services.json',
    },
    android: {
      package: 'com.yourcompany.reactnativeline',
      versionCode: 1,
      adaptiveIcon: {
        foregroundImage: './path/to/adaptive-icon.png',
        backgroundColor: '#ffffff',
      },
      googleServicesFile: './path/to/google-services.json',
      permissions: ['CAMERA'],
    },
    extra: {
      line: {
        ios: {
          channelId: process.env.LINE_IOS_CHANNEL_ID,
          universalLink: process.env.LINE_IOS_UNIVERSAL_LINK,
        },
        android: {
          channelId: process.env.LINE_ANDROID_CHANNEL_ID,
          channelName: process.env.LINE_ANDROID_CHANNEL_NAME,
          channelUri: process.env.LINE_ANDROID_CHANNEL_URI,
        },
      },
    },
  },
};

Make sure you replace the values ​​for the file path, organization and project information for Sentry, and the required LINE configuration with the appropriate values.

Next, create an .env file in your project directory and enter LINE details like LINE_IOS_CHANNEL_ID, LINE_IOS_UNIVERSAL_LINK, LINE_ANDROID_CHANNEL_ID, LINE_ANDROID_CHANNEL_NAME and LINE_ANDROID_CHANNEL_URI with the appropriate values.

After that, run the expo prebuild command to create a bundle that will be used when the exhibition is run.

Next, run the command expo start --dev-client to run the application using the Expo Dev Client.

I came after I submitted the bounty that you created with the username @emibotti TyLee5 at replit.com

**Comment by najil-12** [comment]
> 

but my project is not on expo

**Comment by tnylee** [comment]
Getting the same error. Installed v2.2.0 and iOS target is 13.0.

**Comment by MiteshIts** [comment]
Same issue

**Comment by tranquockhanh0506** [comment]
add:
 use_frameworks! :linkage => :static

      installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end

 in your pod file.

**Comment by najil-12** [comment]
> add: use_frameworks! :linkage => :static
> 
> ```
>   installer.pods_project.build_configurations.each do |config|
>   config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
> end
> ```
> 
> in your pod file.

same issue

**Comment by tranquockhanh0506** [comment]
https://github.com/xmartlabs/react-native-line/issues/107#issuecomment-1715933560
have you handled it yet?  @najil-12
if not.  just follow it

**Comment by najil-12** [comment]
> [#107 (comment)](https://github.com/xmartlabs/react-native-line/issues/107#issuecomment-1715933560) have you handled it yet? @najil-12 if not. just follow it

yes i've added this code in my podfile

**Comment by najil-12** [comment]
> [#107 (comment)](https://github.com/xmartlabs/react-native-line/issues/107#issuecomment-1715933560) have you handled it yet? @najil-12 if not. just follow it

Yes I've added this code in my Podfile. here it is

`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
prepare_react_native_project!
install! 'cocoapods', :deterministic_uuids => false
# use_frameworks!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
permissions_path = '../node_modules/react-native-permissions/ios'
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  use_frameworks! :linkage => :static
end




# pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
# pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
pod 'Firebase', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true 
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'FBSDKLoginKit'
pod 'LineSDKSwift', '~> 5.8.1'        
        target 'RichestLife' do
          config = use_native_modules!
          # pod 'LineSDKSwift', '~> 5.0'
          # project 'RichestLife',
          # 'Debug' => :debug,
          # 'Dev Debug' => :debug,
          # 'Alpha Debug' => :debug,
          # 'QA Debug' => :debug,
          # 'Release' => :release,
          # 'Dev Release' => :release,
          # 'Alpha Release' => :release,
          # 'QA Release' => :release
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RichestLifeTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
`

**Comment by tranquockhanh0506** [comment]
uncomment this line: use_frameworks! :linkage => :static
if u run with ios change version of  react-native-line to 2.1.0
if android run with 2.2.0
add to your podFile:
  installer.pods_project.build_configurations.each do |config|
  config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
end

**Comment by tranquockhanh0506** [comment]
1, after sign in success the confirm popup open your app, right?

**Comment by tranquockhanh0506** [comment]
1 this is default of line , I also don't know how to turn it off :))

**Comment by najil-12** [comment]
@chenkuangkuang  Can you tell me what steps you have taken? also what changes have been made in podfile and version.
And please don't forget to share Podfile, react native and rn-line version.
Thanks

**Comment by tranquockhanh0506** [comment]
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [LineLogin application:app open:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  BOOL handledLine = [LineLogin application:application continue:userActivity restorationHandler:restorationHandler];
  return handledLine;
}
this is my AppDelegate, l don't know why you need to use lineLogin in conjunction with RCTLinkingManager

**Comment by tranquockhanh0506** [comment]
so..why you do not handle in call back value form your react native app
you want to open other app after sign in with line success right?

**Comment by tranquockhanh0506** [comment]
btw, after sign in with line have you received a response from line yet?

**Comment by tranquockhanh0506** [comment]
If you are successfully signing in with Line, I have completed my help. The next problems are not related to signing in with Line, please try to do it bro!

**Comment by Jiayuwalker** [comment]
Same issue here!!
react-native: v0.72.0
react-native-flipper was default installed. I can get it run with `use_frameworks!`. Is there any way to use this library with react-native-flipper co-exist?

**Comment by vietdung97** [comment]
Same issue here:

- react-native: v0.72.4
-  @xmartlabs/react-native-line": "^2.2.0"
-  Xcode 14.3

 My Podfile:
 ```
 def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '13.0'
prepare_react_native_project!

setup_permissions([
  'AppTrackingTransparency',
  # 'BluetoothPeripheral',
  # 'Calendars',
  'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  'Notifications',
  'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'SpeechRecognition',
  # 'StoreKit'
])

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SquareFitnessClient' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'WechatOpenSDK'

  target 'SquareFitnessClientTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    #  添加这段，M1/M2 模拟器能跑起来，wechat 小而美！
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = '$(PODS_ROOT)/../../.env'
        end
      end
    end
    installer.aggregate_targets.first.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']
      end
    end
    # quiet non-module warnings - only interested in fbsdk-next warnings
    installer.pods_project.targets.each do |target|
      if !target.name.include? "react-native-fbsdk-next"
        target.build_configurations.each do |config|
        config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
        end
      end
     end
  end

end

 ```
 
![Screenshot 2023-11-09 at 17 56 31](https://github.com/xmartlabs/react-native-line/assets/50390141/7493d0bd-d791-47c9-b28a-b09e8dfc2b34)

Please help !

**Comment by Jiayuwalker** [comment]
@vietdung97 
I solved it by disabling Flipper and adding `use_frameworks! :linkage => :static`. To disable Flipper, you can refer to https://dev.to/retyui/disable-flipper-on-ci-builds-for-react-native-complete-guide-bnd

**Comment by vietdung97** [comment]
> @vietdung97 I solved it by disabling Flipper and adding `use_frameworks! :linkage => :static`. To disable Flipper, you can refer to https://dev.to/retyui/disable-flipper-on-ci-builds-for-react-native-complete-guide-bnd
I change use_frameworks! :linkage => :static and set NO_FLIPPER = 1. But I get the new error.
![Screenshot 2023-11-13 at 10 58 40](https://github.com/xmartlabs/react-native-line/assets/50390141/385cf33d-25c1-4bbe-bab0-865ba629dd58)

**Comment by Woogie-94** [comment]
```
- #import "RNLine-Swift.h"
+ @import RNLine;
```

**Comment by Peterpann9999** [comment]
> ```
> - #import "RNLine-Swift.h"
> + @import RNLine;
> ```

use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules

**Comment by purrsong-chong** [comment]
Sorry for late close.
I had problem with bridging header.
For some reason, after I recreated bridgin header, the error has gone.

Thank you all for considering my issue.

**Comment by ThangNV1205** [comment]
> Sorry for late close. I had a problem with bridging header. For some reason, after I recreated bridgin header, the error has gone.
> 
> Thank you all for considering my issue.

@purrsong-chong  hey bro, could you give me step-by-step to fix them, I have created {...}-Bridging-Header.h file by auto create by XCode after create Swift file and add #import <RNLine-Swift.h>, in AppDeligate.mm, I add import {...}-Bridging-Header.h. Both clean project, remove DerivedData and deintegrate Pod, after pod install and build from XCode, issues show for Header file

**Comment by purrsong-chong** [comment]
> > Sorry for late close. I had a problem with bridging header. For some reason, after I recreated bridgin header, the error has gone.
> > Thank you all for considering my issue.
> 
> [@purrsong-chong](https://github.com/purrsong-chong) hey bro, could you give me step-by-step to fix them, I have created {...}-Bridging-Header.h file by auto create by XCode after create Swift file and add #import <RNLine-Swift.h>, in AppDeligate.mm, I add import {...}-Bridging-Header.h. Both clean project, remove DerivedData and deintegrate Pod, after pod install and build from XCode, issues show for Header file


I was experiencing the same issue repeatedly, so I referenced this package's implementation code and directly integrated it as a Native Module.

**Comment by kieth1205** [comment]
> > > Sorry for late close. I had a problem with bridging header. For some reason, after I recreated bridgin header, the error has gone.
> > > Thank you all for considering my issue.
> > 
> > 
> > [@purrsong-chong](https://github.com/purrsong-chong) hey bro, could you give me step-by-step to fix them, I have created {...}-Bridging-Header.h file by auto create by XCode after create Swift file and add #import <RNLine-Swift.h>, in AppDeligate.mm, I add import {...}-Bridging-Header.h. Both clean project, remove DerivedData and deintegrate Pod, after pod install and build from XCode, issues show for Header file
> 
> I was experiencing the same issue repeatedly, so I referenced this package's implementation code and directly integrated it as a Native Module.

could you give me instruction to implement as Native Module?
