### ISSUE TITLE
The 'kotlin-android-extensions' Gradle plugin is no longer supported. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

### ISSUE THREAD

**Issue by LucasWilliams2622** [xmartlabs/react-native-line#125]
## My environment
npx react-native info

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.0) != current release (0.74.3)
  
info Fetching system and libraries information...
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1
  Memory: 75.86 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn:
    version: 3.6.4
    path: ~/Documents/GitHub/eparkrae-native-app-repo/node_modules/.bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman:
    version: 2024.04.29.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/tanaakkhcm256/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34-ext8 | Google Play ARM 64 v8a
      - android-34-ext8 | Google Play Intel x86_64 Atom
      - android-34 | Intel x86_64 Atom
      - android-34 | Google TV ARM 64 v8a
      - android-34 | Google TV Intel x86 Atom
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google APIs Intel x86_64 Atom
      - android-34 | Google Play ARM 64 v8a
      - android-34 | Google Play Intel x86_64 Atom
      - android-34 | Google APIs ATD ARM 64
      - android-34 | Google APIs ATD Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/tanaakkhcm256/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

You can run (`react-native -v`) to obtain info and paste it below:

- React: 12.1.1
- React Native:0.73.0
- React Native Line:2.2.0

## Description
I go this error when running app in android studio, i have config app following [Line's Android integration guide](https://developers.line.biz/en/docs/android-sdk/integrate-line-login/) and i got the error about kotlin-android-extensions
### Screenshots
![Screenshot 2024-07-24 at 15 29 49](https://github.com/user-attachments/assets/41e8b54b-357c-43fb-bd25-52e39c43f0fe)

## Steps To Reproduce
1. Install @xmartlabs/react-native-line 
2. Add implementation 'com.linecorp.linesdk:linesdk:latest.release' in android/app/build.gradle
3. Add  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    } in android/app/build.gradle
4. Then run your project in android studio

### Expected behavior
I want to integrate Line login in my react native app
### Actual behavior
The 'kotlin-android-extensions' Gradle plugin is no longer supported. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by carozo** [comment]
Hey @LucasWilliams2622, version 2.2.1 was just released and it includes the fix on https://github.com/xmartlabs/react-native-line/pull/115. Please let me know if solves your issue.
