### ISSUE TITLE
#import <LineSDK/LineSDK.h> file not found

### ISSUE THREAD

**Issue by hoangphan92** [xmartlabs/react-native-line#13]
I run command: `react-native link react-native-line-sdk` and  run ios . It's not working !.
My error: 
![screen shot 2018-04-02 at 8 45 26 pm](https://user-images.githubusercontent.com/25924647/38198500-48b53e32-36b7-11e8-9104-5d0665470f50.png)
I don't know why beacause i added LineSDK.framework ?

**Comment by santiagofm** [comment]
Hey @hoangphan92, are you using cocoapods or linking the LineSDK manually?
If doing it manually: please go to your projects settings > Build Phases tab > Link Binary With Libraries and ensure the lineSDK is on the list.

Cheers,

**Comment by hoangphan92** [comment]
I added LineSDK to  Build Phases ->  Link Binary With Libraries..  into LineLoginManager.xcodeproj and it's work.

**Comment by nonth** [comment]
@santiagofm Hi, I've also facing the same problem with cocoapods, any solutions about this ?

Thanks,

**Comment by oxygenyoyo2** [comment]
I got this error both manual link and pod install. Have any idea to fix this one ? because I tried every way to fix it in a comment.

**Comment by oxygenyoyo2** [comment]
I got the answer

[https://github.com/xmartlabs/react-native-line/issues/17#issuecomment-437581842](https://github.com/xmartlabs/react-native-line/issues/17#issuecomment-437581842)
