### ISSUE TITLE
Missing access token when logout and re-login

### ISSUE THREAD

**Issue by hoangphan92** [xmartlabs/react-native-line#15]
First , I login and get success user_profile.
 ```
LineLogin.login()
      .then(user => {
        console.log(user.profile);
      })
      .catch(err => {
        console.log(err);
      });
```
 Next I logout: 
`LineLogin.logout()`
And, I re-login and it's not show form login Line and log error:

> Error: Missing access token.
>     at createErrorFromErrorData (NativeModules.js:115)
>     at NativeModules.js:78
>     at MessageQueue.__invokeCallback (MessageQueue.js:296)
>     at MessageQueue.js:120
>     at MessageQueue.__guard (MessageQueue.js:218)
>     at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:119)
>     at debuggerWorker.js:71

I debug in LineLoginManager.m and it's jump to line 102:

```
if ([shared isAuthorized])
    {
        [self getProfile:loginResolver // line 102
                rejecter:loginRejecter];
    }
```
I try debugging but it is very difficult for me, please help me !

**Comment by santiagofm** [comment]
Seems to be an [issue](https://github.com/line/line-sdk-starter-ios-v2/issues/17) with the LineSDK...
As a workaround you could remove the check if the user is authorized on the login; just replace the `loginWithPermissions:permissions` with the following code:
```objc
- (void)loginWithPermissions:(NSArray *)permissions
{
    LineSDKLogin *shared = [LineSDKLogin sharedInstance];
    
    if ([shared canLoginWithLineApp])
    {
        if (permissions && [permissions count] > 0) {
            [shared startLoginWithPermissions:permissions];
        } else
        {
            [shared startLogin];
        }
    } else
    {
        if (permissions && [permissions count] > 0) {
            [shared startWebLoginWithPermissions:permissions];
        } else
        {
            [shared startWebLogin];
        }
    }
}
```
