### ISSUE TITLE
Cannot open the return URL. (line3rdp.{iOS bundle ID}://authorize/)

### ISSUE THREAD

**Issue by thangtv17** [xmartlabs/react-native-line#19]
[https://i.imgur.com/aEAlmvV.png](url)
I can't login line in device iOS

**Comment by wktq** [comment]
Same here.

**Comment by vyasishanatc194** [comment]
- add in Info.plist
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            
            <string>line3rdp.$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        </array>
    </dict>
</array>
<key>LSApplicationQueriesSchemes</key>
<array>
    
    <string>lineauth2</string>
</array> 



- add in developer account 
iOS scheme: Set to line3rdp. followed by the bundle identifier. For example, if your bundle identifier is com.example.app, set the iOS scheme to line3rdp.com.example.app. Only one iOS scheme can be specified.

**Comment by eb16** [comment]
Seems @vyasishanatc194 already answered to you guys. I'm closing this issue. 
Every error related  this should be addressed with the new release 🎉  Just follow the steps in the Readme please.

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
