### ISSUE TITLE
The stale token of version 4 conflicts

### ISSUE THREAD

**Issue by ht-jo** [xmartlabs/react-native-line#21]
### Issue

When we upgrade this wrapper from 1.1.0 to 1.2.0. If there are v4 tokens of line, it won't work at getUserProfile function since the Line API server reject their v4 token on v5 sdk.

https://github.com/xmartlabs/react-native-line/blob/dcbdfe3543737dc3f5870411d62f81ffe86a7ec8/ios/LineLoginManager.m#L100-L103

There is no way to clear stale token. The only way is to receive new token from Line API server.

### Workaround

So, I removed that code, when I got the new token from Line login process, stale token issue was resolved.

### Suggest

We need to isolate getUserProfile from loginWithPermissions method.
I'll contribute this by pull request. Thank you.

**Comment by orcunorcun** [comment]
I deleted it also but still doesn't work after login. :/

**Comment by santiagofm** [comment]
hey guys! I've merged this PR and created a tag for the new release.
Unfortunately I'm having trouble accessing npm in order to publish the new version.. so in the meantime you can point directly to the master branch.
Cheers

**Comment by santiagofm** [comment]
1.3.0 has been published to the nom registry
