### ISSUE TITLE
Please fix that library. Some user of my app can't login with it. And if i try to login with web login it say "'scope' is not specified." please help me I have problem with my company because of that problem.

### ISSUE THREAD

**Issue by orcunorcun** [xmartlabs/react-native-line#23]

**Comment by santiagofm** [comment]
Hey there!
If you could show us how to reproduce this issue in our example app(or provide one that has the issue) it would be much appreciated! Theres not much we can do with the info provided.
Cheers

**Comment by orcunorcun** [comment]
When you can release last version on npm?

**Comment by santiagofm** [comment]
@orcunorcun just did! Sorry for the delay, we had misplaced our credentials <|:)
