### ISSUE TITLE
How to get email address?

### ISSUE THREAD

**Issue by seiyata** [xmartlabs/react-native-line#25]
Thank you for the great library.

I was able to retrieve profile information with this lib, but not yet find the way to get email address of the login user.
I confirmed I can pass 'email' and 'openid' to loginWithPermissions() and they are shown on Line authorization screen, but the response from line doesn't contain email.

Could you advise how to get email address? or it's not supported yet?

**Comment by oxygenyoyo2** [comment]
in the LineLoginManager.m you can follow this code below
`#pragma mark - LineSDKLoginDelegate

- (void)didLogin:(LineSDKLogin *)login
      credential:(LineSDKCredential *)credential
         profile:(LineSDKProfile *)profile
           error:(NSError *)error
{
    if (error)
    {
        loginRejecter(nil, nil, error);
    } else
    {
        NSLog(@"==================== credential %@", credential.IDToken.email);
        NSMutableDictionary *result = [NSMutableDictionary new];
        NSDictionary *parsedAccessToken = [self parseAccessToken:[credential accessToken]];
        NSDictionary *parsedProfile = [self parseProfile:profile];
        
        [result setValue:parsedAccessToken forKey:@"accessToken"];
        [result setValue:parsedProfile forKey:@"profile"];
        [result setValue:credential.IDToken.email forKey:@"email"];
        
        loginResolver(result);
    }
}`

try this one

**Comment by santiagofm** [comment]
Hey there! If you want to open a PR with this it would be awesome! Currently we don't have availability to work on it.
Cheers

**Comment by eb16** [comment]
Hey! I will be closing this issue since this should be addressed with the new release 🎉  Just check sending `email` parameter into `scopes` when calling `login` function:

```
const loginResult = await Line.login({ scopes: ['email'] })
```

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
