### ISSUE TITLE
React native version 0.60

### ISSUE THREAD

**Issue by orcunorcun** [xmartlabs/react-native-line#31]
Will you update it for react-native version 0.60? It doesn't work on it now.

**Comment by eb16** [comment]
Hello @orcunorcun ! We're working on a new wrapper that includes latest Line SDK and support for latest react-native version 💪 Soon you'll have news about it

**Comment by storz** [comment]
Hi @eb16. What about a new wrapper now? I hope to hear good news.

**Comment by eb16** [comment]
Hey @storz ! We've been working on the new version, and I can say it is almost there. iOS native side and example app are already done. We're working on Android side, in Kotlin, and after that we will build the library and deploy it. I hope to have a release date, but we're putting all of our effort to release it sooner as possible 💪

**Comment by arianetan31** [comment]
Hello, is there any updates on this? thanks.

**Comment by Turuus** [comment]
> Hello, is there any updates on this? thanks.

Nope.

**Comment by HannanShaikYara** [comment]
Any updates on this? How soon can we expect it to be ready?

**Comment by eb16** [comment]
Hey everyone! Sorry for the late response. I will give you some updates regarding the library advances:

- Android side, in Kotlin, is already done.
- We did a private release to Github packages. We are doing some tests internally with the rn team in Xmartlabs, to ensure it's working properly.
- We have written a README containing documentation about its setup and use in an example app.

Now we are working on implementing the example app with a new design according Line guidelines, working along design team. Also, we want to read over every issue and vulnerability  that was present in the `version 1`, so every concern is contemplated.

We guess that if everything works fine, it will be ready within the following 3 weeks.

**Comment by shubham-noborders** [comment]
> Hey everyone! Sorry for the late response. I will give you some updates regarding the library advances:
> 
> * Android side, in Kotlin, is already done.
> * We did a private release to Github packages. We are doing some tests internally with the rn team in Xmartlabs, to ensure it's working properly.
> * We have written a README containing documentation about its setup and use in an example app.
> 
> Now we are working on implementing the example app with a new design according Line guidelines, working along design team. Also, we want to read over every issue and vulnerability that was present in the `version 1`, so every concern is contemplated.
> 
> We guess that if everything works fine, it will be ready within the following 3 weeks.

Is there any update?

**Comment by nakinthorn** [comment]
any update ?

**Comment by eb16** [comment]
Hello everyone! I'm pleased to announce that the **new version of React Native Line is now live**! 🎉 
Thank you so much for your patience! We will be addressing and answering last version issues.
Please don't hesitate in asking us every doubt or technical problem you have, we will try to reach you as soon as possible 💪 

The new version is published in this new package: https://www.npmjs.com/package/@xmartlabs/react-native-line
Follow the readme to get started !

@orcunorcun @storz @arianetan31 @Turuus @HannanShaikYara @shubham-noborders @nakinthorn
