### ISSUE TITLE
Error onlyWebLogin  cannot be cast from Boolean to String

### ISSUE THREAD

**Issue by star4680** [xmartlabs/react-native-line#46]
I'm currently using

react native: 0.60.5
@xmartlabs/react-native-line : 2.0.1

 const loginResult = await Line.login({
                scopes: ['email', 'profile'],
                botPrompt: 'normal',
                onlyWebLogin : true
})

When adding onlyWebLogin field to loginArguments, the following error occurs :
Value for onlyWeblogin cannot be cast from Boolean to String
checkInstance[ReadablenativeMap.java:141]
getNullableValue[ReadablenativeMap.java:129]
getString[ReadablenativeMap.java:163]
login[RnLine.kt:61]
...

Thank you.

**Comment by nicoache1** [comment]
@star4680  Please try 2.1.0, this issue should be solved in that. I would close the issue, feel free to reopen if the new version doesn't solve the problem.
