### ISSUE TITLE
'RNLine-Swift.h' file not found

### ISSUE THREAD

**Issue by Duya3fithou** [xmartlabs/react-native-line#47]
I am trying follow your example.
1. First I try following the doc but I got this error:
`Use of undeclared identifier 'LineLogin'`
2. I follow your example then I import 
`#import "RNLine-Swift.h"` in `AppDelegate.m`
3. Try to `pod install` but failed
After google searching: 
replace `platform :ios, '9.0'` to `platform :ios, '10.0'`
and add `ENV['SWIFT_VERSION'] = '5'` on top of my podfile
--> pod success
But I still get the error: 
`'RNLine-Swift.h' file not found`

Tks for your lib, pls help

**Comment by nicoache1** [comment]
@Duya3fithou Could you please provide us with more info regarding your environment? (RN Version, etc) and we could check what is happening?

Also another thing did you try to create a bridging-header?

**Comment by Duya3fithou** [comment]
My environment:

1. RN 0.61.5
2. xcode 11.5

what are you mean create bridging-header, can you help me fix this 
by the way, I try run your example and it work.
Can you update the document for more detail. Tks u

**Comment by nicoache1** [comment]
Open the project with your Xcode and then add a new Swift file to the project. Name it as you please and you should get an alert box asking if you would like to create a bridging header.

![1_oracQfdQS1O9oo0P8Slk2g](https://user-images.githubusercontent.com/26419582/86470896-bb709500-bd12-11ea-82da-2709018208f0.png)

The project should do it automatically but something could it be not working, i will check it and if this works for you i wll update the documentation.

**Comment by Duya3fithou** [comment]
tks your support, i create create a bridging header with new Swift file.
-> pod install
and it work fine
But it navigae to my Line application and give alert error "
An error occurred".
After, it auto navigate to safari to site web login line with red warning "
Your device does not have LINE or universal link installed correctly. Please log in with your email address and password."
Run your example. it give error too. 
what happend and how to fix this. tks you

**Comment by nicoache1** [comment]
@Duya3fithou The example app its not configured to work with Universal Links, in order to do that you should follow this guide in the line developer site https://developers.line.biz/en/docs/ios-sdk/swift/setting-up-project/#linking-app-to-channel

**Comment by nicoache1** [comment]
@Duya3fithou 2.1.0 new version with updates in README in order to help you. I will close the issue, feel free to reopen if that doesn't solve your problem

**Comment by PaperMonster** [comment]
> @Duya3fithou You should do the next steps.
> 
> 1 - platform :ios, '10.0' en Podfile line:1
> 2 - add **use_frameworks!** en Podfile line:3
> 3 - comment everything related with flipper because it didnt work with `use_frameworks!` enabled

In my case after following these 3 steps. I had to clean Xcode project as well to make the error disappear.

**Comment by najil-12** [comment]
> @Duya3fithou Could you please provide us with more info regarding your environment? (RN Version, etc) and we could check what is happening?
> 
> Also another thing did you try to create a bridging-header?



My environment:

RN 0.71.4
xcode 14.3


please help

**Comment by tranquockhanh0506** [comment]
lib như cặc
