### ISSUE TITLE
[Android] Error while login

### ISSUE THREAD

**Issue by cuongnm2301** [xmartlabs/react-native-line#57]
## Your environment

You can run (`react-native -v`) to obtain info and paste it below:

- React: 16.11.0
- React Native: 0.61.5
- React Native Line: 2.0.1

## Description

While login android, but ios is fine.
Can you tell me how to debug your native module on android, many thks
### Screenshots

![image](https://user-images.githubusercontent.com/44488353/88454053-ca241500-ce96-11ea-9f49-09521cfda61a.png)

![image](https://user-images.githubusercontent.com/44488353/88454106-1e2ef980-ce97-11ea-8e51-57ade7d005f7.png)

## Steps To Reproduce

1. Already add 

`
<resources>
<string name="line_channel_id" translatable="false">1654402186</string>
</resources>
`

2. Set minSdkVersion to 17

### Expected behavior

- get token

### Actual behavior

- get unknow error

**Comment by santiagofm** [comment]
Hey @cuongnm2301! Would you mind providing us with a sample project that reproduces the issue? Just tested the example app and everything works as expected. Any other information like Android version or device would be appreciated too.

You can debug the native code as you would with any native android app: https://developer.android.com/studio/debug.

**Comment by santiagofm** [comment]
bet, are you using 2.0.1 or 2.1.0 ?

**Comment by cuongnm2301** [comment]
I forgot add my package name to my line channel....
btw, tks for help
