### ISSUE TITLE
[iOS] Error: Use of undeclared identifier 'LineLogin'

### ISSUE THREAD

**Issue by liayoo** [xmartlabs/react-native-line#58]
## Description

When building in Xcode, I keep getting the error "Use of undeclared identifier 'LineLogin'" in AppDelegate.m.

## Code

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  [LineLogin setupWithChannelID:@"....." universalLinkURL:nil];
  
  return YES;
}

- (BOOL)application:(UIApplication *)application 
            openURL:(NSURL *)url 
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [LineLogin application: application open:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  BOOL handledLine = [LineLogin application:application continue:userActivity restorationHandler:restorationHandler];
  return handledLine;
}
```

### Package versions

- Xcode: 11.2.1
- React Native: 0.61.4
- React Native Line: 2.1.0

**Comment by santiagofm** [comment]
Hello @liayoo, how are you importing the library ? Did you follow all the steps outlined in [using with objective-c](https://github.com/xmartlabs/react-native-line#using-objective-c) ?

**Comment by liayoo** [comment]
Hi @santiagofm, thanks for the prompt response! And Yes, I've followed all 5 steps in the link you provided.

**Comment by santiagofm** [comment]
Have you imported the library to be used in the `AppDelegate` ? Like we do on the example app: https://github.com/xmartlabs/react-native-line/blob/master/example/ios/AppDelegate.m#L15

I'll update the README with this step since it's missing

**Comment by liayoo** [comment]
Yes, I saw the example and tried adding the line, but it gave me another error: "'RNLine-Swift.h' file not found".

**Comment by Nateethorn** [comment]
i got the same issue

**Comment by liayoo** [comment]
@Nateethorn Hey we actually fixed the build issue! Try `@import RNLine;` instead of `#import "RNLine-Swift.h` in AppDelegate.m

**Comment by acro5piano** [comment]
@liayoo Thanks you saved my time a lot!

**Comment by hanayashiki** [comment]
For those who're suffering from use_frameworks! incompatible dependencies, use:
```
use_frameworks! :linkage => :static
```
instead of barely `use_frameworks!`

**Comment by raj-xcerpt** [comment]
Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.
