### ISSUE TITLE
Any solution to work this lib without using use_framework!

### ISSUE THREAD

**Issue by cuongnm2301** [xmartlabs/react-native-line#61]
## Description
I am working both with **react-native-line** and **react-native-maps**. To install react-native-maps I must remove use_framework! in podfile. Any solution for this 

### Package versions

- React:
- React Native:
- React Native Line:

**Comment by yjb94** [comment]
@cuongnm2301 have you tried https://github.com/xmartlabs/react-native-line/issues/58?
it kinda seems not using `use_frameworks!` only matters to importing strategy. try using `@import RNLine;`

**Comment by Esxiel** [comment]
I can confrm this, on RN 63.4. You dont need the use_frameworks!, you just need to import it correctly using `@import RNLine`

**Comment by tructran2598** [comment]
@yjb94 @Esxiel  I'm using RN 63.4 and using `@import RNLine` too, but keep getting `Use of undeclared identifier LineLogin`, does anyone can help? 😢
