### ISSUE TITLE
Undefined symbols: _RCTRegisterModule

### ISSUE THREAD

**Issue by shenjo** [xmartlabs/react-native-line#62]
1. use react-native cli create a project. 
2. add this lib, and follow the [setup] five steps.
3. xcode build error.
![image](https://user-images.githubusercontent.com/13912646/103213647-3d9be800-4949-11eb-96c5-21d3f46a290d.png)

Undefined symbols for architecture arm64:
  "_RCTRegisterModule", referenced from:
      _initialize_LineLogin in LineLogin-138bef0e233c3c4437231f24c868aa03c1831bc8c7a540fc7b932c7a4d7a2881.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can anyone help me ?

**Comment by nicoache1** [comment]
Hi @shenjo could you provide more info (versions, example) about the issue?
