### ISSUE TITLE
cannot build ios got Use of undeclared identifier 'LineLogin' 

### ISSUE THREAD

**Issue by nazacity** [xmartlabs/react-native-line#63]
i can perfectly run npm run ios
however I have tried to build product and got Use of undeclared identifier 'LineLogin'

i hae tried @import RNLine; on the appdelefate.m

**Comment by nicoache1** [comment]
Hi @nazacity are you using swift or objective C? did you follow the steps in the `readme`? Could you provide more info about the issue?

**Comment by raj-xcerpt** [comment]
Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.

**Comment by phuocantd** [comment]
> #import "RNLine-Swift.h"

`RNLine-Swift.h file not found` when add top <b>AppDlegate.mm</b>

**Comment by purrsong-chong** [comment]
> Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.

It's not working..
