### ISSUE TITLE
Customisation toast message for success login 

### ISSUE THREAD

**Issue by sengchunyee** [xmartlabs/react-native-line#64]
Is there any way to change or disable the login success toast message instead of showing "Login successful!"?
Toast message during onlyWebLogin:true is disable.

Currently using:
"react-native": "0.63.3",
@xmartlabs/react-native-line": "^2.1.0"

**Comment by santiagofm** [comment]
Hi @sengchunyee !

Is that Android or iOS? What toast are you referring to? Can you point at the issue on the example app ?

**Comment by sengchunyee** [comment]
Hi, its on Android 
Device: Xiaomi Mi Note 10

Could not find it on the example app, I've upload a simple repo to reproduce the issue
Hereby attach some screenshots as well
![photo_2021-02-25_12-17-57](https://user-images.githubusercontent.com/33580909/109102538-10f72780-7764-11eb-82ab-3029c13a6ec5.jpg)
![photo_2021-02-25_12-18-02](https://user-images.githubusercontent.com/33580909/109102542-12285480-7764-11eb-9aed-4b84f2fb53ab.jpg)
![photo_2021-02-25_12-18-08](https://user-images.githubusercontent.com/33580909/109102544-13598180-7764-11eb-82df-244908cff0f9.jpg)



[https://github.com/sengchunyee/AwesomeProject](url)

**Comment by santiagofm** [comment]
@sengchunyee Thank you! Theres nothing special/different on that repo you provided 🤔 

Quick question, do you have the Line app installed on that device or is it just opening a webview ?

**Comment by sengchunyee** [comment]
@santiagofm 

The Line app is installed on the device. 
Still finding the way to edit the toast message.

**Comment by santiagofm** [comment]
Hey @sengchunyee! Are you signing in using the "Log in with smartphone" method?
Searching through documentation I just found this help article that mentions a "Login Successful" notification:
![image](https://user-images.githubusercontent.com/6749415/109502455-c7664f80-7a77-11eb-84a1-9ccbafde1cf6.png)
