### ISSUE TITLE
Module 'RNLine' not found error in AppDelegate.m

### ISSUE THREAD

**Issue by yppon** [xmartlabs/react-native-line#73]
## Description

When I try to build in Xcode 12.4 - Apple Silicon Mac, "Module 'RNLine' not found" error occurred at `@import RNLine` in AppDelegate.m.

I use `@import RNLine` instead of `#import "RNLine-Swift.h` in reference to https://github.com/xmartlabs/react-native-line/issues/58#issuecomment-683408528

How can I resolve this error ... ?

![image](https://user-images.githubusercontent.com/5195591/121331197-9c7e7800-c951-11eb-9e24-2db008ad4653.png)

### Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Line: 2.1.0
- Xcode: 12.4
- Apple Silicon Mac

**Comment by raj-xcerpt** [comment]
Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.

**Comment by phuocantd** [comment]
> Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.

not working for me
