### ISSUE TITLE
@import RNLine;  but still Use of undeclared identifier 'LineLogin'

### ISSUE THREAD

**Issue by edemchen** [xmartlabs/react-native-line#76]
As subject, 'LineLogin' cannot be defined, no matter if I install 'LineSDKSwift' or 'LineSDKSwift/ObjC' or nothing.

I modified the Podfile to install LineSDK as below :

platform :ios, '10.0'
#use_frameworks!    # It cause many issues so that I mask it.
target 'CSApp3' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Line Login
  pod 'LineSDKSwift/ObjC', '~> 5.0'
......................................................................................

Then amend Info.plist :

        <key>CFBundleURLSchemes</key>
			<array>
				...................... (ignore) .............................
                                  
                                  <string>line3rdp.$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		................... (ignore) .......................
                
                <string>lineauth2</string>
	</array>
	
and then, modify AppDelegate.m

@import RNLine;

........................ (ignore) ...........................
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
        #ifdef FB_SONARKIT_ENABLED
          InitializeFlipper(application);
        #endif

          RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
          RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                           moduleName:@"MyAppName"
                                                    initialProperties:nil];

  
          ............................... (ignore) ..............................
          [LineLogin setupWithChannelID:@"OurLineID" universalLinkURL:nil];
          return YES;
}

//
// Handle redirection back to the app from Line
//
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [LineLogin application:app open:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  BOOL handledLine = [LineLogin application:application continue:userActivity restorationHandler:restorationHandler];
  return handledLine;
}

**Comment by raj-xcerpt** [comment]
Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.
