### ISSUE TITLE
Build error in iOS : Use of undeclared identifier 'LineLogin'

### ISSUE THREAD

**Issue by edem** [xmartlabs/react-native-line#77]
## Your environment

- node : v14.17.3
- React Native: 0.64.2
- react-native-cli: 2.0.1
- React Native Line: "@xmartlabs/react-native-line": "^2.1.0"
- Platform : iOS

## Description

Use of undeclared identifier 'LineLogin'

I have read some links as below and tried to fix it. But all of them do not work.
https://github.com/xmartlabs/react-native-line/issues/58
https://github.com/xmartlabs/react-native-line#using-objective-c

## Steps To Reproduce

1. install

   yarn add @xmartlabs/react-native-line
   cd ios
   
2. edit Podfile as below : ( I mask 'use_frameworks!'. It cause many compatible error. I tried 'use_frameworks! :linkage => :static'. It cause error too. )

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
#use_frameworks! :linkage => :static
#use_frameworks!

target 'CSApp3' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  #Line Login --> I have tried both ways.
  pod 'LineSDKSwift', '~> 5.0'
  #pod 'LineSDK', '~> 5.0'
end

3. pod install :
   
    pod install
    cd ..
    
4. edit AppDelegate.m to import header file : ( I have tried two ways )

#import "RNLine-Swift.h"
or 
@import RNLine;

5. edit method 'didFinishLaunchingWithOptions' in AppDelegate.m  

add this line before return :

[LineLogin setupWithChannelID:@"1111111111" universalLinkURL:nil];

6. build and get error :

Use of undeclared identifier 'LineLogin'

### Expected behavior

I am looking forward to building success.

### Actual behavior

Use of undeclared identifier 'LineLogin'

**Comment by raj-xcerpt** [comment]
Moving **#import "RNLine-Swift.h"** to top in **AppDelegate.m** solved the issue for me.

**Comment by phuocantd** [comment]
same issue
