### ISSUE TITLE
The SDK version is out of date

### ISSUE THREAD

**Issue by blackbing** [xmartlabs/react-native-line#91]
The latest iOS SDK version is [5.8.1](https://github.com/line/line-sdk-ios-swift), and the latest Android SDK version is [5.7.0](https://github.com/line/line-sdk-android).

Besides, the usage in react-native had some change. 

I open a pull request for the upgrade, and also work on our project. https://github.com/xmartlabs/react-native-line/pull/90

May the power be with the repo.

**Comment by emibotti** [comment]
Hey @blackbing , sorry for the late response! Thank you for your contributions!!
We have released version 2.2.0. Please check if the issue is still happening, and let me know!
