### ISSUE TITLE
How to config library in react-native 0.69

### ISSUE THREAD

**Issue by phuocantd** [xmartlabs/react-native-line#93]
## Your environment

You can run (`react-native -v`) to obtain info and paste it below:

- React:18.2.0
- React Native:0.69.1
- React Native Line:2.1.0

## Description

I want to use lib but I do not config it for my project even though I followed the instructions and example!

**Comment by jeong-sik** [comment]
I'm using 0.69.4 and it builds without problems. Of course, using this library as is now will cause problems. I use yarn patch to change the settings. Do you have any problems? Can't build?

**Comment by phuocantd** [comment]
> I'm using 0.69.4 and it builds without problems. Of course, using this library as is now will cause problems. I use yarn patch to change the settings. Do you have any problems? Can't build?
@jeong-sik 
Can you share me an example with RN0.69.4?

**Comment by VanDinh18** [comment]
i'm using 0.69.3. i using pod install and have error The 'Pods-App-GhostPostTests' target has transitive dependencies that include statically linked binaries: (Flipper-Boost-iOSX). how to fix it

**Comment by emibotti** [comment]
Hey @phuocantd , @VanDinh18 and @jeong-sik , sorry for the late response!
We have released version 2.2.0. Please check if the issue is still happening, and let me know!
