### ISSUE TITLE
App crashes after clicking on Line Sign-in Button

### ISSUE THREAD

**Issue by PedramGhdi** [xmartlabs/react-native-line#97]
Hi, I'm using react-native on ios but when I click on sign in, the app crashes.
I think it has a problem with new versions of react-native maybe?

react-native-cli: 2.0.1
react-native: 0.68.2
and SDK is the latest version. Higher than 5

**Comment by emibotti** [comment]
Hey @PedramGhdi, sorry for the late response! We have released version 2.2.0. Please check if the issue is still happening, and let me know!
