### ISSUE TITLE
Android Emulator won't run.

### ISSUE THREAD

**Issue by woongkiki** [xmartlabs/react-native-line#98]
## Description

I completed the settings according to read.me, but the Android build does not work with the following error.
ios runs correctly.

I am getting an error in RNLine.kt.

error what went wrong
/node_modules/@xmartlabs/react-native-line/android/src/main/java/com/xmartlabs/rnline/RNLine.kt: (262, 36): Unresolved reference: to

- React: 17.0.2
- React Native: 0.67.3
- React Native Line:  verybuy/react-native-line#8dcc99d

**Comment by emibotti** [comment]
Hey @woongkiki , sorry for the late response! We have released version 2.2.0. Please check if the issue is still happening, and let me know!
